export type ColorOption = {
  name: string;
  code: string;
};

export const catalogColorOptions: ColorOption[] = [
  { name: "Alice Blue", code: "#F0F8FF" },
  { name: "Antique White", code: "#FAEBD7" },
  { name: "Aqua", code: "#00FFFF" },
  { name: "Aquamarine", code: "#7FFFD4" },
  { name: "Azure", code: "#F0FFFF" },
  { name: "Beige", code: "#F5F5DC" },
  { name: "Bisque", code: "#FFE4C4" },
  { name: "Black", code: "#111827" },
  { name: "Blanched Almond", code: "#FFEBCD" },
  { name: "Blue", code: "#2563EB" },
  { name: "Blue Violet", code: "#8A2BE2" },
  { name: "Blush", code: "#F4C2C2" },
  { name: "Brown", code: "#7C2D12" },
  { name: "Burgundy", code: "#800020" },
  { name: "Burly Wood", code: "#DEB887" },
  { name: "Cadet Blue", code: "#5F9EA0" },
  { name: "Camel", code: "#C19A6B" },
  { name: "Champagne", code: "#F7E7CE" },
  { name: "Chartreuse", code: "#7FFF00" },
  { name: "Chocolate", code: "#D2691E" },
  { name: "Coral", code: "#FF7F50" },
  { name: "Cornflower Blue", code: "#6495ED" },
  { name: "Cornsilk", code: "#FFF8DC" },
  { name: "Cream", code: "#FFFDD0" },
  { name: "Crimson", code: "#DC143C" },
  { name: "Cyan", code: "#06B6D4" },
  { name: "Dark Blue", code: "#00008B" },
  { name: "Dark Brown", code: "#3F2305" },
  { name: "Dark Cyan", code: "#008B8B" },
  { name: "Dark Goldenrod", code: "#B8860B" },
  { name: "Dark Gray", code: "#374151" },
  { name: "Dark Green", code: "#006400" },
  { name: "Dark Khaki", code: "#BDB76B" },
  { name: "Dark Magenta", code: "#8B008B" },
  { name: "Dark Olive", code: "#556B2F" },
  { name: "Dark Orange", code: "#FF8C00" },
  { name: "Dark Orchid", code: "#9932CC" },
  { name: "Dark Red", code: "#8B0000" },
  { name: "Dark Salmon", code: "#E9967A" },
  { name: "Dark Sea Green", code: "#8FBC8F" },
  { name: "Dark Slate Blue", code: "#483D8B" },
  { name: "Dark Slate Gray", code: "#2F4F4F" },
  { name: "Dark Turquoise", code: "#00CED1" },
  { name: "Dark Violet", code: "#9400D3" },
  { name: "Deep Pink", code: "#FF1493" },
  { name: "Deep Sky Blue", code: "#00BFFF" },
  { name: "Denim", code: "#1560BD" },
  { name: "Dim Gray", code: "#696969" },
  { name: "Dodger Blue", code: "#1E90FF" },
  { name: "Dusty Rose", code: "#C9A9A6" },
  { name: "Emerald", code: "#50C878" },
  { name: "Firebrick", code: "#B22222" },
  { name: "Floral White", code: "#FFFAF0" },
  { name: "Forest Green", code: "#228B22" },
  { name: "Fuchsia", code: "#D946EF" },
  { name: "Gainsboro", code: "#DCDCDC" },
  { name: "Ghost White", code: "#F8F8FF" },
  { name: "Gold", code: "#FFD700" },
  { name: "Goldenrod", code: "#DAA520" },
  { name: "Gray", code: "#6B7280" },
  { name: "Green", code: "#16A34A" },
  { name: "Green Yellow", code: "#ADFF2F" },
  { name: "Honeydew", code: "#F0FFF0" },
  { name: "Hot Pink", code: "#FF69B4" },
  { name: "Ivory", code: "#FFFFF0" },
  { name: "Jade", code: "#00A86B" },
  { name: "Khaki", code: "#F0E68C" },
  { name: "Lavender", code: "#E6E6FA" },
  { name: "Lavender Blush", code: "#FFF0F5" },
  { name: "Lawn Green", code: "#7CFC00" },
  { name: "Lemon Chiffon", code: "#FFFACD" },
  { name: "Light Blue", code: "#ADD8E6" },
  { name: "Light Coral", code: "#F08080" },
  { name: "Light Cyan", code: "#E0FFFF" },
  { name: "Light Goldenrod", code: "#FAFAD2" },
  { name: "Light Gray", code: "#D1D5DB" },
  { name: "Light Green", code: "#90EE90" },
  { name: "Light Pink", code: "#FFB6C1" },
  { name: "Light Salmon", code: "#FFA07A" },
  { name: "Light Sea Green", code: "#20B2AA" },
  { name: "Light Sky Blue", code: "#87CEFA" },
  { name: "Light Slate Gray", code: "#778899" },
  { name: "Light Steel Blue", code: "#B0C4DE" },
  { name: "Light Yellow", code: "#FFFFE0" },
  { name: "Lilac", code: "#C8A2C8" },
  { name: "Lime", code: "#00FF00" },
  { name: "Lime Green", code: "#32CD32" },
  { name: "Linen", code: "#FAF0E6" },
  { name: "Magenta", code: "#FF00FF" },
  { name: "Maroon", code: "#800000" },
  { name: "Mauve", code: "#E0B0FF" },
  { name: "Medium Aquamarine", code: "#66CDAA" },
  { name: "Medium Blue", code: "#0000CD" },
  { name: "Medium Orchid", code: "#BA55D3" },
  { name: "Medium Purple", code: "#9370DB" },
  { name: "Medium Sea Green", code: "#3CB371" },
  { name: "Medium Slate Blue", code: "#7B68EE" },
  { name: "Medium Spring Green", code: "#00FA9A" },
  { name: "Medium Turquoise", code: "#48D1CC" },
  { name: "Medium Violet Red", code: "#C71585" },
  { name: "Midnight Blue", code: "#191970" },
  { name: "Mint", code: "#98FF98" },
  { name: "Mint Cream", code: "#F5FFFA" },
  { name: "Misty Rose", code: "#FFE4E1" },
  { name: "Moccasin", code: "#FFE4B5" },
  { name: "Mustard", code: "#FFDB58" },
  { name: "Navajo White", code: "#FFDEAD" },
  { name: "Navy", code: "#1E3A8A" },
  { name: "Nude", code: "#E3BC9A" },
  { name: "Off White", code: "#FAF9F6" },
  { name: "Old Lace", code: "#FDF5E6" },
  { name: "Olive", code: "#4D7C0F" },
  { name: "Olive Drab", code: "#6B8E23" },
  { name: "Orange", code: "#FFA500" },
  { name: "Orange Red", code: "#FF4500" },
  { name: "Orchid", code: "#DA70D6" },
  { name: "Pale Goldenrod", code: "#EEE8AA" },
  { name: "Pale Green", code: "#98FB98" },
  { name: "Pale Turquoise", code: "#AFEEEE" },
  { name: "Pale Violet Red", code: "#DB7093" },
  { name: "Papaya Whip", code: "#FFEFD5" },
  { name: "Peach", code: "#FFE5B4" },
  { name: "Peach Puff", code: "#FFDAB9" },
  { name: "Peru", code: "#CD853F" },
  { name: "Pink", code: "#FFC0CB" },
  { name: "Plum", code: "#DDA0DD" },
  { name: "Powder Blue", code: "#B0E0E6" },
  { name: "Purple", code: "#800080" },
  { name: "Rebecca Purple", code: "#663399" },
  { name: "Red", code: "#DC2626" },
  { name: "Rose", code: "#E11D48" },
  { name: "Rosy Brown", code: "#BC8F8F" },
  { name: "Royal Blue", code: "#4169E1" },
  { name: "Saddle Brown", code: "#8B4513" },
  { name: "Salmon", code: "#FA8072" },
  { name: "Sandy Brown", code: "#F4A460" },
  { name: "Sea Green", code: "#2E8B57" },
  { name: "Sea Shell", code: "#FFF5EE" },
  { name: "Sienna", code: "#A0522D" },
  { name: "Silver", code: "#C0C0C0" },
  { name: "Sky Blue", code: "#87CEEB" },
  { name: "Slate Blue", code: "#6A5ACD" },
  { name: "Slate Gray", code: "#708090" },
  { name: "Snow", code: "#FFFAFA" },
  { name: "Spring Green", code: "#00FF7F" },
  { name: "Steel Blue", code: "#4682B4" },
  { name: "Stone", code: "#78716C" },
  { name: "Tan", code: "#D2B48C" },
  { name: "Taupe", code: "#483C32" },
  { name: "Teal", code: "#008080" },
  { name: "Thistle", code: "#D8BFD8" },
  { name: "Tomato", code: "#FF6347" },
  { name: "Transparent White", code: "#FFFFFF" },
  { name: "Turquoise", code: "#40E0D0" },
  { name: "Violet", code: "#EE82EE" },
  { name: "Wheat", code: "#F5DEB3" },
  { name: "White", code: "#F9FAFB" },
  { name: "White Smoke", code: "#F5F5F5" },
  { name: "Wine", code: "#7F1D1D" },
  { name: "Yellow", code: "#FACC15" },
  { name: "Yellow Green", code: "#9ACD32" },
];
